### ISSUE TITLE
ModuleNotFoundError: No module named 'ina238'

### ISSUE THREAD

**Issue by rbx** [GSI-HPC/py-ina238#1]
When using via hatch shell I get the following error:

```
user@node:~/dev/py-ina238$ hatch build
[sdist]
dist/ina238-0.0.1.tar.gz

[wheel]
dist/ina238-0.0.1-py3-none-any.whl
user@node:~/dev/py-ina238$ hatch shell
user@node:~/dev/py-ina238$ source "/home/user/.local/share/hatch/env/virtual/ina238/GNc33cL8/ina238/bin/activate"
(ina238) user@node:~/dev/py-ina238$ python
Python 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ti.ina238
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/dev/py-ina238/ti/__init__.py", line 6, in <module>
    import ina238
ModuleNotFoundError: No module named 'ina238'
>>> 
```

Seems it can be fixed by modifying:
```diff
diff --git a/ti/__init__.py b/ti/__init__.py
index c977b8e..8f9905d 100644
--- a/ti/__init__.py
+++ b/ti/__init__.py
@@ -3,4 +3,4 @@
 PKGNAME = 'py-ina238'
 VERSION = '0.0.1'
 
-import ina238
+from . import ina238
```

**Comment by dennisklein** [comment]
thx, fixed in cdd3aced8921c20df6da7f155100a84b928070c4
